### ISSUE TITLE
Issue With 'always-semicolon'?

### ISSUE THREAD

**Issue by wylie** [d4rkr00t/css-comb-atom#16]
I'm seeing an issue with the `always-semicolon` option in the config.

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: css-comb package, v2.4.0

My config contains `"always-semicolon": true`, but it doesn't always add the missing semicolon on individual CSS declarations. 

Here are some things I've noticed:
- If the last declaration is the only one missing it's semicolon, running css-comb-atom adds it. If any other declarations are missing their semicolon they don't get added.
- If all declarations are missing their semicolons then no sorting happens and only the last semicolon get added.

In trying to get my config how I want it I've been playing around with this block of CSS:

``` css
.test {
    position: absolute;
    display: block;
    padding: 0 10px 0 0;
    margin: auto;
    color: red;
    border-color: green;
}
```

Here is a link to my `.csscomb.json` file: https://www.dropbox.com/s/c4roltd95x4cb1b/csscomb.json?dl=0

Here is an image of my css-comb-atom settings
<img width="746" alt="screen shot 2016-01-21 at 3 02 27 pm" src="https://cloud.githubusercontent.com/assets/74600/12492820/1984e87c-c050-11e5-95df-d2dbebf9ca17.png">
