### ISSUE TITLE
Csscomb only runs on save

### ISSUE THREAD

**Issue by lukasoppermann** [d4rkr00t/css-comb-atom#6]
Neither the shortcut, nor click run on the menu has any effect. 
Only saving it activates the csscomb script and shows the notification.

Disabling `on save` does not change this issue.

**Comment by d4rkr00t** [comment]
Thanks for report. I'll try to find out why it's happening.

**Comment by lukasoppermann** [comment]
Hey, while it does run, it seems like it does different things.

When saving it adds the ; at the end, put when pressing the keyboard shortcut it does not.

However, it displays the alter in both cases.

**Comment by d4rkr00t** [comment]
Hi, can you show some examples, some styles which were transformed diffrenetly? And can you try to process your file by standalone csscomb? Something like this (if you have global installed csscomb):

```
csscomb -c ~/.csscomb.json style.css
```

Because this plugin just call csscomb's on opened file or selected lines and put csscomb output back to the editor.

**Comment by lukasoppermann** [comment]
Hey, 

so my input is this

``` css
.pseudo-element(){
    top: 1px;
    position: absolute;
    display: block;
    content: ''
}
```

when pressing ctrl+alt+c I get this (nothing changed, but the notification appears)

``` css
.pseudo-element(){
    top: 1px;
    position: absolute;
    display: block;
    content: ''
}

```

on Save I get the "correct" result

``` css
.pseudo-element()
{
    position: absolute;
    top: 1px;
    display: block;
    content: '';
}
```
